### ISSUE TITLE
missing infos in DOCS

### ISSUE THREAD

**Issue by papilinou** [circuitdiagram/components#110] opened 2020-11-08 14:18 UTC
In DOCS>Components>Render Options>Grid add : in  Gitpod>File>Settings>open preferences>Circuit Diagram>set:
Diagram Show Grid
Render a grid behind the component.(shown in blue).
In DOCS>Components>Render Options>Debug Layout: add in  Gitpod>File>preferences>Circuit Diagram>set:
Render component layout information Diagram Debug Layout.
In DOCS>Components>Finishing:> circuit-diagramcli component my_component.xml -o my_component.cdcom
miss "-" between diagram and cli.> circuit-diagram-cli component my_component.xml -o my_component.cdcom

**Comment by papilinou** [comment] 2020-11-09 18:16
May be not the right place to set this issue,so i set the same on Circuit Diagram.

**Comment by SamuelFisher** [comment] 2020-11-09 20:38
Duplicate of https://github.com/circuitdiagram/circuitdiagram/issues/28.

**Closed by SamuelFisher** 2020-11-09 20:38 UTC
