### ISSUE TITLE
display error on components options when importing

### ISSUE THREAD

**Issue by papilinou** [circuitdiagram/components#107] opened 2020-11-04 16:09 UTC
when importing from PC a cddx project, inductor value is set to show even when set to off when exporting,and toggle switch show closed even when set to open at export,external input same,set reverse when re-importing,but if exporting the project to png ,settings are ok on png export.
I think that when components are reloading in display, you don't take care to  components options like "display value" "reversed" and so on but they still are in cddx file.

**Comment by papilinou** [comment] 2020-11-09 18:16
May be not the right place to set this issue,so i set the same on Circuit Diagram.

**Comment by SamuelFisher** [comment] 2020-11-09 21:04
Duplicate of https://github.com/circuitdiagram/circuitdiagram/issues/27.

**Closed by SamuelFisher** 2020-11-09 21:04 UTC
